#version: '3'
#services:
#  mongodb:
#    image: mongo
#    ports:
#      - 27017:27017
#    volumes:
#      - mongo:/data
#
#  mongo-express:
#    image: mongo-express
#    restart: always
#    ports:
#      - 8081:8081
#    environment:
#      - ME_CONFIG_MONGODB_ADMINUSERNAME=VANDU
#      - ME_CONFIG_MONGODB_ADMINPASSWORD=VANDU
#      - ME_CONFIG_MONGODB_SERVER=mongodb
#
#volumes:
#  mongo: {}