spring:
  data:
    mongodb:

      host: localhost   # must match the service name in docker-compose.yml
      port: 27017
      database: chat_app
      authentication-database: admin
server:
  port: 8088
